services:
  arangar-digital:
    build:
      context: .
      dockerfile: Dockerfile
    image: arangar-digital:latest
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    restart: unless-stopped
